# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20170710_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
    ]
