# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_nestedcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
